-- MySQL Script generated by MySQL Workbench
-- Sun Feb 27 02:03:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Profesores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Profesores` (
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripción` VARCHAR(150) NOT NULL,
  `Foto` BLOB NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alumnos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alumnos` (
  `Nombre` VARCHAR(20) NOT NULL,
  `Celular` CHAR(9) NOT NULL,
  `DNI` CHAR(8) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cursos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `Nombre` VARCHAR(20) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Horario` DATETIME NOT NULL,
  `Alumnos_Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Nombre`, `Alumnos_Nombre`),
  CONSTRAINT `fk_Cursos_Alumnos1`
    FOREIGN KEY (`Alumnos_Nombre`)
    REFERENCES `mydb`.`Alumnos` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cursos_Alumnos1_idx` ON `mydb`.`Cursos` (`Alumnos_Nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Profesores_has_Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Profesores_has_Cursos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Profesores_has_Cursos` (
  `Profesores_Nombre` VARCHAR(20) NOT NULL,
  `Cursos_Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Profesores_Nombre`, `Cursos_Nombre`),
  CONSTRAINT `fk_Profesores_has_Cursos_Profesores`
    FOREIGN KEY (`Profesores_Nombre`)
    REFERENCES `mydb`.`Profesores` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesores_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_Nombre`)
    REFERENCES `mydb`.`Cursos` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Profesores_has_Cursos_Cursos1_idx` ON `mydb`.`Profesores_has_Cursos` (`Cursos_Nombre` ASC) VISIBLE;

CREATE INDEX `fk_Profesores_has_Cursos_Profesores_idx` ON `mydb`.`Profesores_has_Cursos` (`Profesores_Nombre` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
