-- MySQL Script generated by MySQL Workbench
-- Sun Feb 27 00:16:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `ID_cliente` INT NOT NULL,
  `Apellidos` VARCHAR(20) NULL,
  `Nombres` VARCHAR(20) NULL,
  `Dirección` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(10) NULL,
  `Pais` VARCHAR(10) NULL,
  `Celular` CHAR(9) NULL,
  `Fax` VARCHAR(45) NULL,
  `Fecha ingreso` DATE NULL,
  `Ind_vigente` CHAR(1) NULL,
  PRIMARY KEY (`ID_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artículo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Artículo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Artículo` (
  `Id_artículo` INT NOT NULL,
  `descripción` VARCHAR(100) NULL,
  `precio unitario` FLOAT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`Id_artículo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vendedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vendedor` (
  `Id_vendedor` INT NOT NULL,
  `Nombre` VARCHAR(10) NULL,
  PRIMARY KEY (`Id_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `ID_pedido` INT NOT NULL,
  `Clientes_ID_cliente` INT NOT NULL,
  `Vendedor_Id_vendedor` INT NOT NULL,
  `Fecha pedido` DATE NULL,
  `Impuesto` FLOAT NULL,
  `Estado` VARCHAR(9) NULL,
  PRIMARY KEY (`ID_pedido`, `Clientes_ID_cliente`, `Vendedor_Id_vendedor`),
  INDEX `fk_Pedido_Clientes_idx` (`Clientes_ID_cliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Vendedor1_idx` (`Vendedor_Id_vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Clientes`
    FOREIGN KEY (`Clientes_ID_cliente`)
    REFERENCES `mydb`.`Clientes` (`ID_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Vendedor1`
    FOREIGN KEY (`Vendedor_Id_vendedor`)
    REFERENCES `mydb`.`Vendedor` (`Id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Detalle pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Detalle pedido` (
  `Pedido_ID_pedido` INT NOT NULL,
  `Artículo_Id_artículo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` FLOAT NULL,
  `Subtotal` FLOAT NULL,
  PRIMARY KEY (`Pedido_ID_pedido`, `Artículo_Id_artículo`),
  INDEX `fk_Detalle pedido_Artículo1_idx` (`Artículo_Id_artículo` ASC) VISIBLE,
  INDEX `fk_Detalle pedido_Pedido1_idx` (`Pedido_ID_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle pedido_Artículo1`
    FOREIGN KEY (`Artículo_Id_artículo`)
    REFERENCES `mydb`.`Artículo` (`Id_artículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle pedido_Pedido1`
    FOREIGN KEY (`Pedido_ID_pedido`)
    REFERENCES `mydb`.`Pedido` (`ID_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
