-- MySQL Script generated by MySQL Workbench
-- Sun Feb 27 01:55:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mesa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `Código_mesa` CHAR(8) NOT NULL,
  `Número_mesa` INT NOT NULL,
  `Descripción` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Código_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mozos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mozos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mozos` (
  `Código_mozo` CHAR(8) NOT NULL,
  `Nombre_mozo` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(25) NOT NULL,
  `Fecha_entrada` DATE NOT NULL,
  `Zona_rest` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código_mozo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Platos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Platos` (
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripción` VARCHAR(200) NOT NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Mesa_Código_mesa` CHAR(8) NOT NULL,
  `Platos_Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Mesa_Código_mesa`, `Platos_Nombre`),
  CONSTRAINT `fk_Pedidos_Mesa`
    FOREIGN KEY (`Mesa_Código_mesa`)
    REFERENCES `mydb`.`Mesa` (`Código_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Platos1`
    FOREIGN KEY (`Platos_Nombre`)
    REFERENCES `mydb`.`Platos` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pedidos_Platos1_idx` ON `mydb`.`Pedidos` (`Platos_Nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa_has_Mozos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mesa_has_Mozos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mesa_has_Mozos` (
  `Mesa_Código_mesa` CHAR(8) NOT NULL,
  `Mozos_Código_mozo` CHAR(8) NOT NULL,
  PRIMARY KEY (`Mesa_Código_mesa`, `Mozos_Código_mozo`),
  CONSTRAINT `fk_Mesa_has_Mozos_Mesa1`
    FOREIGN KEY (`Mesa_Código_mesa`)
    REFERENCES `mydb`.`Mesa` (`Código_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mesa_has_Mozos_Mozos1`
    FOREIGN KEY (`Mozos_Código_mozo`)
    REFERENCES `mydb`.`Mozos` (`Código_mozo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mesa_has_Mozos_Mozos1_idx` ON `mydb`.`Mesa_has_Mozos` (`Mozos_Código_mozo` ASC) VISIBLE;

CREATE INDEX `fk_Mesa_has_Mozos_Mesa1_idx` ON `mydb`.`Mesa_has_Mozos` (`Mesa_Código_mesa` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
